apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - bot-rbac.yaml
  - bot-to-supervisor-egress.yaml
  - bot-to-postgres-egress.yaml
  - bot-to-s3-egress.yaml
  - bot-to-kv-cache-egress.yaml
  - game-to-bot-agent-egress.yaml
