//! The emitter: turn a validated [`PromptTree`] into the generated `prompts.rs`
//! module, and the build-script entry that writes it.
//!
//! [`generate`] is the pure, testable core (tree → Rust source); [`emit`] is the
//! build-script wrapper that writes the source to `$OUT_DIR/prompts.rs` and
//! registers the prompt tree for rebuild-on-change.

mod items;
mod rust;
mod schema;

use std::path::Path;

use items::{emit_params, emit_prompt, emit_tool};

use super::error::PromptError;
use super::model::{PromptFile, PromptKind, PromptTree};

/// An indentation-aware source buffer. Four spaces per level; `open`/`close`
/// bracket a nested block so callers never hand-manage indentation.
#[derive(Default)]
struct Code {
    buf: String,
    depth: usize,
}

impl Code {
    fn line(&mut self, text: &str) {
        if !text.is_empty() {
            for _ in 0..self.depth {
                self.buf.push_str("    ");
            }
            self.buf.push_str(text);
        }
        self.buf.push('\n');
    }

    fn open(&mut self, text: &str) {
        self.line(text);
        self.depth += 1;
    }

    fn close(&mut self, text: &str) {
        self.depth = self.depth.saturating_sub(1);
        self.line(text);
    }

    fn blank(&mut self) {
        self.buf.push('\n');
    }

    fn finish(self) -> String {
        self.buf
    }
}

/// Load and validate the prompt tree under `prompts_dir`, then emit the
/// generated module as a source string.
///
/// # Errors
///
/// Propagates any [`PromptError`] from loading and validating the tree (IO,
/// structural, or cross-file violations), each naming the offending file.
pub fn generate(prompts_dir: &Path) -> Result<String, PromptError> {
    let tree = super::validate::load(prompts_dir)?;
    Ok(render_tree(&tree))
}

/// Build-script entry: write the generated module to `$OUT_DIR/prompts.rs` and
/// register the prompt tree for rebuild-on-change. Call it from a consumer's
/// `build.rs`; include the result with
/// `include!(concat!(env!("OUT_DIR"), "/prompts.rs"))`.
///
/// # Errors
///
/// Returns a [`PromptError`] if `OUT_DIR` is unset (not run from a build
/// script), if writing `prompts.rs` fails, or if loading/validating the tree
/// fails.
pub fn emit(prompts_dir: &Path) -> Result<(), PromptError> {
    let out_dir = std::env::var_os("OUT_DIR").ok_or_else(|| PromptError::Io {
        path: prompts_dir.to_path_buf(),
        message: "OUT_DIR is not set — emit must be called from a build script".to_owned(),
    })?;
    emit_to(prompts_dir, Path::new(&out_dir))
}

/// The testable core of [`emit`]: generate the module, write it to
/// `<out_dir>/prompts.rs`, and register rebuild-on-change. Split out so it can be
/// exercised with a temporary directory rather than the process `OUT_DIR`.
fn emit_to(prompts_dir: &Path, out_dir: &Path) -> Result<(), PromptError> {
    let source = generate(prompts_dir)?;
    let dest = out_dir.join("prompts.rs");
    std::fs::write(&dest, source).map_err(|err| PromptError::Io {
        path: dest.clone(),
        message: err.to_string(),
    })?;
    register_rerun(prompts_dir)?;
    Ok(())
}

/// Tell cargo to re-run the build when the prompt directory or any prompt file
/// changes, so an edit is picked up by the next `cargo build`.
fn register_rerun(prompts_dir: &Path) -> Result<(), PromptError> {
    println!("cargo:rerun-if-changed={}", prompts_dir.display());
    for path in super::validate::collect_md_files(prompts_dir)? {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    Ok(())
}

/// Emit the whole tree: a banner, then one block per file in id-sorted order.
fn render_tree(tree: &PromptTree) -> String {
    let mut code = Code::default();
    code.line("// @generated by grizzly-prompt-lib — do not edit by hand.");
    for file in tree.files.values() {
        code.blank();
        emit_file(&mut code, file, tree);
    }
    code.finish()
}

fn emit_file(code: &mut Code, file: &PromptFile, tree: &PromptTree) {
    match &file.kind {
        PromptKind::Prompt { body, variables } => {
            emit_prompt(code, &file.id, body, variables);
        }
        PromptKind::Tool {
            wire_name,
            description,
            schema,
            ..
        } => emit_tool(code, &file.id, wire_name, description, schema, tree),
        PromptKind::Params { schema } => emit_params(code, &file.id, schema),
    }
}

#[cfg(test)]
#[path = "tests/emit.rs"]
mod tests;
