// @generated by grizzly-prompt-lib — do not edit by hand.

pub struct Disclaimer;

impl Disclaimer {
    #[must_use]
    pub fn render() -> String {
        String::from("Gary can make mistakes. Double-check anything important before relying on it.")
    }
}

pub struct EditFile;

impl EditFile {
    pub const NAME: &'static str = "edit_file";

    #[must_use]
    pub fn spec() -> grizzly_prompt_lib::ToolSpec {
        grizzly_prompt_lib::ToolSpec {
            name: Self::NAME,
            description: "Edit a configuration file on the server, then verify and roll back on failure.",
            parameters: grizzly_prompt_lib::__private::serde_json::json!({
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "path to the file on the server's data volume"
                    },
                    "mode": {
                        "type": "string",
                        "description": "whether to replace the whole file or append to it",
                        "enum": ["replace", "append"]
                    },
                    "count": {
                        "type": "integer",
                        "description": "number of lines to write; omit to write the whole payload"
                    }
                },
                "required": ["path", "mode"],
                "additionalProperties": false
            }),
        }
    }
}

#[derive(serde::Deserialize)]
pub struct EditFileParams {
    pub path: String,
    pub mode: EditFileMode,
    #[serde(default)]
    pub count: Option<i64>,
}

#[derive(serde::Deserialize)]
pub enum EditFileMode {
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "append")]
    Append,
}

pub struct Greeting<'a> {
    pub name: &'a str,
}

impl Greeting<'_> {
    #[must_use]
    pub fn render(self) -> String {
        let mut out = String::new();
        out.push_str("Hello ");
        out.push_str(self.name);
        out.push_str(", I'm Gary. Tell me what you'd like to do with your servers.");
        out
    }
}

#[derive(serde::Deserialize)]
pub struct NameParams {
    pub name: String,
}

pub struct Ping;

impl Ping {
    pub const NAME: &'static str = "ping";

    #[must_use]
    pub fn spec() -> grizzly_prompt_lib::ToolSpec {
        grizzly_prompt_lib::ToolSpec {
            name: Self::NAME,
            description: "Check whether the server is responding.",
            parameters: grizzly_prompt_lib::__private::serde_json::json!({
                "type": "object",
                "properties": {},
                "additionalProperties": false
            }),
        }
    }
}

pub struct StartServer;

impl StartServer {
    pub const NAME: &'static str = "start_server";

    #[must_use]
    pub fn spec() -> grizzly_prompt_lib::ToolSpec {
        grizzly_prompt_lib::ToolSpec {
            name: Self::NAME,
            description: "Start a stopped server and report its address once it's ready.",
            parameters: grizzly_prompt_lib::__private::serde_json::json!({
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "the server name to act on"
                    }
                },
                "required": ["name"],
                "additionalProperties": false
            }),
        }
    }
}
